export const IMAGE_PATHS = {
    ANYLIGHTMODE: "/image/LightMode/Any.png",
    ANYDARKMODE: "/image/DarkMode/Any.png",
    SUVLIGHTMODE: "/image/LightMode/Suv.png",
    SUVDARKMODE: "/image/DarkMode/Suv.png",
    SEDANLIGHTMODE: "/image/LightMode/Sedan.png",
    SEDANDARKMODE: "/image/DarkMode/Sedan.png",
    SPORTLIGHTMODE: "/image/LightMode/Sport.png",
    SPORTDARKMODE: "/image/DarkMode/Sport.png",
    TRUCKLIGHTMODE: "/image/LightMode/Truck.png",
    TRUCKDARKMODE: "/image/DarkMode/Truck.png",
    VANLIGHTMODE: "/image/LightMode/Van.png",
    VANDARKMODE: "/image/DarkMode/Van.png",
    COMPACTLIGHTMODE: "/image/LightMode/Compact.png",
    COMPACTDARKMODE: "/image/DarkMode/Compact.png",
    MINIVANLIGHTMODE: "/image/LightMode/MiniVan.png",
    MINIVANDARKMODE: "/image/DarkMode/MiniVan.png",
    HEAVYDUTYLIGHTMODE: "/image/LightMode/HeavyDuty.png",
    HEAVYDUTYDARKMODE: "/image/DarkMode/HeavyDuty.png",
};